insert into user_tab(name, login, password) values('Admin','admin','$2a$10$bTiY2gJ1zQf9NuGLueISReN0Ub0PiDt5pXsHrmShArHimkcixd1ES');
insert into user_tab(name, login, password) values('User','user','$2a$10$VDI4TSnBWaPCg2.Ua4ov1uLPiX76PGtzTog96WeawFxka2ytu.z2e');

insert into role_tab(name) values('ROLE_ADMIN');
insert into role_tab(name) values('ROLE_USER');

insert into user_roles(user_id,role_id) values(1,1);
insert into user_roles(user_id,role_id) values(1,2);
insert into user_roles(user_id,role_id) values(2,2);

insert into automaker_tab(name, country_origin, user_id) values('AUDI', 'ALEMANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('BENTLEY', 'REINO UNIDO', 1);
insert into automaker_tab(name, country_origin, user_id) values('BUGATTI', 'FRANÇA', 1);
insert into automaker_tab(name, country_origin, user_id) values('LAMBORGHINI', 'ITALIA', 1);
insert into automaker_tab(name, country_origin, user_id) values('PORCHE', 'ALEMANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('SEAT', 'ESPANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('VOLKSWAGEM', 'ALEMANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('BUILK', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('CADILLAC', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('CHEVROLET', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('GMC', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('DAIHATSU', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('LEXUS', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('TOYOTA', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('HYUNDAI', 'COREIA DO SUL', 1);
insert into automaker_tab(name, country_origin, user_id) values('KIA', 'COREIA DO SUL', 1);
insert into automaker_tab(name, country_origin, user_id) values('FORD', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('LINCOLN', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('RENAULT', 'FRANÇA', 1);
insert into automaker_tab(name, country_origin, user_id) values('ALPINE', 'FRANÇA', 1);
insert into automaker_tab(name, country_origin, user_id) values('NISSAN', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('MITSUBISHI', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('ALFA ROMEO', 'ITALIA', 1);
insert into automaker_tab(name, country_origin, user_id) values('CHRYSLER', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('FERRARI', 'ITALIA', 1);
insert into automaker_tab(name, country_origin, user_id) values('FIAT', 'ITALIA', 1);
insert into automaker_tab(name, country_origin, user_id) values('JEEP', 'ESTADOS UNIDOS', 1);
insert into automaker_tab(name, country_origin, user_id) values('PEUGEOT', 'FRANÇA', 1);
insert into automaker_tab(name, country_origin, user_id) values('HONDA', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('SUZUKI', 'JAPÃO', 1);
insert into automaker_tab(name, country_origin, user_id) values('BMW', 'ALEMANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('MINI', 'REINO UNIDO', 1);
insert into automaker_tab(name, country_origin, user_id) values('ROLLS-ROYCE', 'REINO UNIDO', 1);
insert into automaker_tab(name, country_origin, user_id) values('MERCEDES-BENZ', 'ALEMANHA', 1);
insert into automaker_tab(name, country_origin, user_id) values('MAYBACH', 'ALEMANHA', 1);

insert into vehicle_tab(name, model, engine, color, automaker_id, user_id) values('A3 sedan','2023','S line 40 TFSI S tronic - 204cv','Branco ibis',1,1);
insert into vehicle_tab(name, model, engine, color, automaker_id, user_id) values('A3 sedan','2023','S line 40 TFSI S tronic - 2.0 TFSI - 204cv','Azul Turbo',1,1);
insert into vehicle_tab(name, model, engine, color, automaker_id, user_id) values('A4 Sedan','2023','Prestige 40 TFSI S tronic - 2.0 TFSI - 204cv','Preto Brilhante',1,1);
insert into vehicle_tab(name, model, engine, color, automaker_id, user_id) values('320i GP','2023','184cv','Branco Alpino',31,1);